[package]
name = "adapter"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
kernel.workspace = true
shared.workspace = true
sqlx.workspace = true
tokio.workspace = true
anyhow.workspace = true
derive-new.workspace = true
