[package]
name = "api"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
axum.workspace = true
tokio.workspace = true
kernel.workspace = true
shared.workspace = true
registry.workspace = true
adapter.workspace = true
